name: Bump version
on:
  push:
    tags:
      - v*
jobs:
  bump-version:
    name: Bump version in package.json
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Bump Version of package.json
        uses: ramonpaolo/bump-version@v2.3.1
        with:
          # This sets the tag that you created, e.g. v1.0.0
          tag: ${{ github.ref_name }}
          commit: true
          branch_to_push: 'main'
