name: Bump version
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
        type: string
jobs:
  bump-version:
    name: Bump version in package.json
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      TAG_NAME: ${{ inputs.tag || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.TAG_NAME }}

      - name: Change version in package.json
        uses: jossef/action-set-json-field@v2
        with:
          file: package.json
          field: version
          value: ${{ env.TAG_NAME }}

      - name: Print package.json
        run: cat package.json

      - name: Create Pull Request for new version
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Bump version to ${{ env.TAG_NAME }}'
          branch: ${{ env.TAG_NAME }}
          base: main
          title: 'Bump version to ${{ env.TAG_NAME }}'
          body: 'Automated pull requested created because a tag with the name ${{ env.TAG_NAME }} was pushed to the repo.'
