name: Bump version
on:
  push:
    tags:
      - v*
jobs:
  bump-version:
    name: Bump version in package.json
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Change version in package.json
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ github.ref_name }}

      - name: Create Pull Request for new version
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Bump version to ${{ github.ref_name }}'
          branch: ${{ github.ref_name }}
          title: 'Bump version to ${{ github.ref_name }}'
          body: 'Automated pull requested created because a tag with the name ${{ github.ref_name }} was pushed to the repo.'
