name: Publish package to GitHub Packages
on:
  workflow_run:
    workflows: ['Bump version']
    types: [completed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      TAG_NAME: ${{ inputs.tag || github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ env.TAG_NAME }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:lib

      - name: Create .npmrc file with access to Github Packages
        uses: ferluisxd/create-npmrc@3
        with:
          org_name: guardian
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: pnpm publish --no-git-checks --report-summary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
