name: Publish package to GitHub Packages
on:
  workflow_run:
    workflows: ['Bump version']
    types: [completed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Version to publish'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:lib

      - name: Configure access to Github Packages
        run: pnpm config set @guardian:registry https://npm.pkg.github.com

      - name: Publish
        run: pnpm publish --no-git-checks --report-summary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
